replicaCount: 1

image:
  repository: sudolicious1/todolist-backend
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: http
  protocol: TCP

labels:
  app: backend
  app.kubernetes.io/name: backend
  app.kubernetes.io/instance: backend

selector:
  app: backend

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

vault:
  enabled: true
  addr: "http://vault.vault:8200"
  role: "backend"
  authPath: "auth/test-k8s" 
  secretPath: "kv-v2/data/database/postgres"
  serviceAccount: "vault-auth"
  agentInjectTemplate: |
    {{- with secret "kv-v2/data/database/postgres" -}}
    DB_HOST="{{ .Data.data.host }}"
    DB_USER="{{ .Data.data.user }}"
    DB_NAME="{{ .Data.data.database }}"
    DB_PASSWORD="{{ .Data.data.password }}"
    {{- end }}

config:
  host: "0.0.0.0"
  port: "8080"
  debug: "false"

resources: {}

externalDatabase:
  host: "postgres-postgresql"
  port: "5432"
  database: "todolist"
  user: "postgres"

