replicaCount: 1

image:
  repository: sudolicious1/todolist-backend
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

container:
  port: 8080

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "8080"
  - name: DB_HOST
    value: "postgres-postgresql"
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    value: "postgres"
  - name: DB_NAME
    value: "todolist"

resources: {}

postgresql:
  existingSecret: "postgres-secret"
