apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.config.host | quote }}
  PORT: {{ .Values.config.port | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  
  DB_HOST: {{ .Values.config.db.host | quote }}
  DB_PORT: {{ .Values.config.db.port | quote }}
  DB_NAME: {{ .Values.config.db.name | quote }}
  DB_USER: {{ .Values.config.db.user | quote }}
