apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        vault.hashicorp.com/agent-inject: {{ .Values.vault.enabled | quote }}
        vault.hashicorp.com/agent-init-only: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/addr: {{ .Values.vault.addr | quote }}
        vault.hashicorp.com/auth-path: {{ .Values.vault.authPath | quote }}
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-db-creds: {{ .Values.vault.secretPath | quote }}
        vault.hashicorp.com/agent-inject-template-db-creds: |
{{ .Values.vault.agentInjectTemplate | indent 10 }}
        {{- if .Values.annotations }}
        {{- toYaml .Values.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.vault.serviceAccount | quote }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: metrics
              containerPort: 9090
          command: ["/bin/sh", "-c", "sleep 5 && source /vault/secrets/db-creds && exec ./todolist-app"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
