apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgresql
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: data-postgres-postgresql-0
