global:
  postgresql:
    auth:
      username: "postgres"
      database: "todolist"
      existingSecret: postgres-secret
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
        userPasswordKey: POSTGRES_PASSWORD 

primary:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 1Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
