replicaCount: 1

image:
  repository: sudolicious1/todolist-frontend
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30007

backend:
  serviceName: "backend"
  servicePort: 8080

env:
  REACT_APP_API_BASE_URL: "/api"

resources: {}
